documentTitle: 'Controlled Vocabulary for Audiovisual Core variant: List of Terms'
current_iri:
doc_created:
doc_modified:
publisher:
license_statement:
license_uri:
citation: 'Audiovisual Core Maintenance Group. 2023. Controlled Vocabulary for Audiovisual
  Core variant: List of Terms. Biodiversity Information Standards (TDWG). http://rs.tdwg.org/ac/doc/variant/2023-02-24'
creator: TDWG Audiovisual Core Maintenance Group
comment:
accessUrl:
browserRedirectUri:
dcterms_isPartOf:
abstract: Audiovisual Core uses the terms ac:variant and ac:variantLiteral to provide
  information about the size, extent, and availability of the Service Access Point
  of a media item. This controlled vocabulary provides values for those terms.
