- contributor_iri: https://orcid.org/0000-0003-4365-3135
  contributor_literal: Steven J Baskauf
  contributor_role: lead author
  role_uri: http://www.wikidata.org/entity/Q482980
  affiliation: Vanderbilt University Heard Libraries
  affiliation_uri: http://www.wikidata.org/entity/Q16849893

- contributor_iri: https://orcid.org/0000-0003-0623-6682
  contributor_literal: Matthew Blissett
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Global Biodiversity Information Facility
  affiliation_uri: http://www.wikidata.org/entity/Q1531570

- contributor_iri: http://www.wikidata.org/entity/Q100599637
  contributor_literal: Douglas Boyer
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Duke University
  affiliation_uri: http://www.wikidata.org/entity/Q168751
