documentTitle: Audiovisual Core Guide
current_iri:
doc_created:
doc_modified:
publisher:
license_statement:
license_uri:
citation: Audiovisual Core Maintenance Group. 2023. Audiovisual Core Guide. Biodiversity
  Information Standards (TDWG). http://rs.tdwg.org/ac/doc/guide/2023-02-24
creator:
comment:
accessUrl:
browserRedirectUri:
dcterms_isPartOf:
abstract: The Audiovisual Core is a set of vocabularies designed to represent metadata
  for biodiversity multimedia resources and collections. This non-normative document
  provides some background to the aims and uses of the standard.
