- contributor_iri: https://orcid.org/0000-0001-6496-1423
  contributor_literal: Matt Woodburn
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Natural History Museum, London
  affiliation_uri: http://www.wikidata.org/entity/Q309388

- contributor_iri: https://orcid.org/0000-0002-8347-0942
  contributor_literal: Kate Webbink
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Field Museum of Natural History
  affiliation_uri: http://www.wikidata.org/entity/Q1122595

- contributor_iri: https://orcid.org/
  contributor_literal: Janeen Jones
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: 
  affiliation_uri: http://www.wikidata.org/entity/

- contributor_iri: https://orcid.org/
  contributor_literal: Sharon Grant
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: 
  affiliation_uri: http://www.wikidata.org/entity/

- contributor_iri: https://orcid.org/
  contributor_literal: Deborah Paul
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: 
  affiliation_uri: http://www.wikidata.org/entity/

- contributor_iri: https://orcid.org/
  contributor_literal: Maarten Trekels
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: 
  affiliation_uri: http://www.wikidata.org/entity/

- contributor_iri: https://orcid.org/
  contributor_literal: Quentin Groom
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: 
  affiliation_uri: http://www.wikidata.org/entity/

- contributor_iri: https://orcid.org/
  contributor_literal: Sarah Vincent
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: 
  affiliation_uri: http://www.wikidata.org/entity/

- contributor_iri: https://orcid.org/
  contributor_literal: Gabi Droege
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: 
  affiliation_uri: http://www.wikidata.org/entity/

- contributor_iri: https://orcid.org/
  contributor_literal: William Ulate
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: 
  affiliation_uri: http://www.wikidata.org/entity/

- contributor_iri: https://orcid.org/
  contributor_literal: Mike Trizna
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: 
  affiliation_uri: http://www.wikidata.org/entity/

- contributor_iri: https://orcid.org/
  contributor_literal: Niels Raes
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: 
  affiliation_uri: http://www.wikidata.org/entity/

- contributor_iri: https://orcid.org/
  contributor_literal: Jutta Buschbom
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: 
  affiliation_uri: http://www.wikidata.org/entity/
