versionDate: "2023-04-26"
utcOffset: -05:00
docIri: http://rs.tdwg.org/ac/doc/part/
mediaType: text/markdown
lastVersionAccessUri: 
lastVersionRedirectUri: 
standardIri: http://www.tdwg.org/standards/638
