versionDate: "2023-06-28"
utcOffset: -05:00
docIri: http://rs.tdwg.org/dwc/doc/list/
mediaType: text/markdown
lastVersionAccessUri: 
lastVersionRedirectUri: # I don't think this actually does anything, so ignore it for now.
standardIri: http://www.tdwg.org/standards/450
