versionDate: "2022-02-23"
docIri: http://rs.tdwg.org/ac/doc/subtype/
mediaType: text/markdown
lastVersionAccessUri: https://raw.githubusercontent.com/tdwg/ac/master/docs/subtype-2020-10-13.md
standardIri: http://www.tdwg.org/standards/638
