versionDate: "2023-02-24"
utcOffset: -06:00
docIri: http://rs.tdwg.org/ac/doc/subtype/
mediaType: text/markdown
lastVersionAccessUri: https://raw.githubusercontent.com/tdwg/ac/master/docs/subtype-2022-02-23.md
standardIri: http://www.tdwg.org/standards/638
