versionDate: "2023-02-24"
utcOffset: -06:00
docIri: http://rs.tdwg.org/ac/doc/variant/
mediaType: text/markdown
lastVersionAccessUri: https://raw.githubusercontent.com/tdwg/ac/master/docs/variant-2020-10-13.md
standardIri: http://www.tdwg.org/standards/638
