documentTitle: Audiovisual Core Introduction
current_iri:
doc_created:
doc_modified:
publisher:
license_statement: 
license_uri:
citation: Audiovisual Core Maintenance Group. 2023. Audiovisual Core Introduction. Biodiversity
  Information Standards (TDWG). http://rs.tdwg.org/ac/doc/introduction/2023-02-24
creator:
comment:
accessUrl:
browserRedirectUri:
dcterms_isPartOf:
abstract: 'The Audiovisual Core is a set of vocabularies designed to represent metadata
  for biodiversity multimedia resources and collections. These vocabularies aim to
  represent information that will help to determine whether a particular resource
  or collection will be fit for some particular biodiversity science application before
  acquiring the media. Among others, the vocabularies address such concerns as the
  management of the media and collections, descriptions of their content, their taxonomic,
  geographic, and temporal coverage, and the appropriate ways to retrieve, attribute
  and reproduce them. '
