documentTitle: "Controlled Vocabulary for Audiovisual Core subjectPart: List of Terms"
current_iri: http://rs.tdwg.org/ac/doc/part/
doc_created: '2023-04-26'
doc_modified: '2023-04-26'
publisher: Biodiversity Information Standards (TDWG)
license_statement: Licensed under a Creative Commons Attribution 4.0 International (CC BY) License.
license_uri: http://creativecommons.org/licenses/by/4.0/
citation: "Views Controlled Vocabularies Task Group. 2023. Controlled Vocabulary for Audiovisual Core 
  subjectPart: List of Terms. Biodiversity Information Standards (TDWG). http://rs.tdwg.org/ac/doc/part/2023-04-26"
creator: TDWG Views Controlled Vocabularies Task Group
comment: ''
accessUrl: https://github.com/tdwg/ac/raw/master/docs/part/index.md
browserRedirectUri: https://ac.tdwg.org/part/
dcterms_isPartOf: http://www.tdwg.org/standards/638
abstract: "The Audiovisual Core term subjectPart describes the part of an organism morphology, behaviour, environment depicted in a media 
  item or region of interest. The subjectPart Controlled Vocabulary provides terms that should be used as values for ac:subjectPart and its 
  literal-valued analog ac:subjectPartLiteral."
