# To use this configuration file, it must be in the process directory from which the
# process.py script is run. Typically, a copy is stored with the modifications CSV file.

# Date assigned to all versions, usually the date of approval by the Executive Committee
date_issued: '2023-09-05'

# UTC offset for the computer running the script
local_offset_from_utc: -05:00

# Only relevant when new term lists or vocabularies are created. It does nothing when
# existing terms are changed. Categories:
# 1: Simple vocabulary
# 2: Simple controlled vocabulary
# 3: Controlled vocabluary with broader hierarchy
vocab_type: 1

# Permanent IRI for the list of terms document that is associated with this vocabulary.
# This is needed to automatically update the date_modified value of the list of terms document 
# using the date_issued value above.
list_of_terms_iri: http://rs.tdwg.org/ac/doc/termlist/

namespaces:

# Repeat the following data for each namespace

# For existing term lists, MUST be namespace assigned by issuing organization. For TDWG
# term lists, MUST follow conventional TDWG IRI patterns.
- namespace_uri: http://rs.tdwg.org/ac/terms/

  # Standard namespace abbreviation for the namespace IRI.
  pref_namespace_prefix: ac

  # Database name for associated directories and files. MUST NOT contain spaces. SHOULD use
  # lowerCamelCase. Borrowed term lists SHOULD use naming convention of Darwin and Audiovisual Cores.
  database: audubon

  # Set to true if namespace not issued by TDWG and in the rs.tdwg.org domain. 
  # Set to false if namespace issued by TDWG.
  borrowed: false

  # Set to true if a new term list that has never been processed before. Otherwise, set to false.
  new_term_list: false

  # Normally set to false except for non-versioned namespaces like decisions.
  utility_namespace: false

  # Path to hand-edited changes CSV file. Relative to process directory from which the
  # process.py script is run.
  modifications_file_path: ac-revisions/ac_fix_errors_2023-09-05/audubon.csv

  # For TDWG-minted terms, SHOULD be set to empty string (Termlist IRI will be set to be
  # the same as the namespace IRI). For borrowed terms, mint an IRI that conforms to the 
  # TDWG termlist IRI pattern.
  termlist_uri: ''

  # Label used for the term list in machine-readable metadata.
  label: Core terms defined by Audiovisual Core

  # Description of the term list used in machine-readable metadata.
  description: This term list includes all currently valid terms that have been defined in the core Audiovisual Core namespace ac:.

# For existing term lists, MUST be namespace assigned by issuing organization. For TDWG
# term lists, MUST follow conventional TDWG IRI patterns.
- namespace_uri: http://purl.org/dc/elements/1.1/

  # Standard namespace abbreviation for the namespace IRI.
  pref_namespace_prefix: dc

  # Database name for associated directories and files. MUST NOT contain spaces. SHOULD use
  # lowerCamelCase. Borrowed term lists SHOULD use naming convention of Darwin and Audiovisual Cores.
  database: dc-for-ac

  # Set to true if namespace not issued by TDWG and in the rs.tdwg.org domain. 
  # Set to false if namespace issued by TDWG.
  borrowed: true

  # Set to true if a new term list that has never been processed before. Otherwise, set to false.
  new_term_list: false

  # Normally set to false except for non-versioned namespaces like decisions.
  utility_namespace: false

  # Path to hand-edited changes CSV file. Relative to process directory from which the
  # process.py script is run.
  modifications_file_path: ac-revisions/ac_fix_errors_2023-09-05/dc-for-ac.csv

  # For TDWG-minted terms, SHOULD be set to empty string (Termlist IRI will be set to be
  # the same as the namespace IRI). For borrowed terms, mint an IRI that conforms to the 
  # TDWG termlist IRI pattern.
  termlist_uri: 'http://rs.tdwg.org/ac/dc/'

  # Label used for the term list in machine-readable metadata.
  label: Audiovisual Core terms borrowed from the Dublin Core legacy namespace

  # Description of the term list used in machine-readable metadata.
  description: This list includes terms borrowed by Audiovisual Core from the legacy (http://purl.org/dc/elements/1.1/) Dublin Core namespace.

# For existing term lists, MUST be namespace assigned by issuing organization. For TDWG
# term lists, MUST follow conventional TDWG IRI patterns.
- namespace_uri: http://purl.org/dc/terms/

  # Standard namespace abbreviation for the namespace IRI.
  pref_namespace_prefix: dcterms

  # Database name for associated directories and files. MUST NOT contain spaces. SHOULD use
  # lowerCamelCase. Borrowed term lists SHOULD use naming convention of Darwin and Audiovisual Cores.
  database: dcterms-for-ac

  # Set to true if namespace not issued by TDWG and in the rs.tdwg.org domain. 
  # Set to false if namespace issued by TDWG.
  borrowed: true

  # Set to true if a new term list that has never been processed before. Otherwise, set to false.
  new_term_list: false

  # Normally set to false except for non-versioned namespaces like decisions.
  utility_namespace: false

  # Path to hand-edited changes CSV file. Relative to process directory from which the
  # process.py script is run.
  modifications_file_path: ac-revisions/ac_fix_errors_2023-09-05/dcterms-for-ac.csv

  # For TDWG-minted terms, SHOULD be set to empty string (Termlist IRI will be set to be
  # the same as the namespace IRI). For borrowed terms, mint an IRI that conforms to the 
  # TDWG termlist IRI pattern.
  termlist_uri: 'http://rs.tdwg.org/ac/dcterms/'

  # Label used for the term list in machine-readable metadata.
  label: Audiovisual Core terms borrowed from the Dublin Core terms namespace

  # Description of the term list used in machine-readable metadata.
  description: This list includes terms borrowed by Audiovisual Core from the terms (http://purl.org/dc/terms/) Dublin Core namespace.

# For existing term lists, MUST be namespace assigned by issuing organization. For TDWG
# term lists, MUST follow conventional TDWG IRI patterns.
- namespace_uri: http://ns.adobe.com/exif/1.0/

  # Standard namespace abbreviation for the namespace IRI.
  pref_namespace_prefix: exif

  # Database name for associated directories and files. MUST NOT contain spaces. SHOULD use
  # lowerCamelCase. Borrowed term lists SHOULD use naming convention of Darwin and Audiovisual Cores.
  database: exif-for-ac

  # Set to true if namespace not issued by TDWG and in the rs.tdwg.org domain. 
  # Set to false if namespace issued by TDWG.
  borrowed: true

  # Set to true if a new term list that has never been processed before. Otherwise, set to false.
  new_term_list: false

  # Normally set to false except for non-versioned namespaces like decisions.
  utility_namespace: false

  # Path to hand-edited changes CSV file. Relative to process directory from which the
  # process.py script is run.
  modifications_file_path: ac-revisions/ac_fix_errors_2023-09-05/exif-for-ac.csv

  # For TDWG-minted terms, SHOULD be set to empty string (Termlist IRI will be set to be
  # the same as the namespace IRI). For borrowed terms, mint an IRI that conforms to the 
  # TDWG termlist IRI pattern.
  termlist_uri: 'http://rs.tdwg.org/ac/exif/'

  # Label used for the term list in machine-readable metadata.
  label: EXIF-specific terms from the XMP specification borrowed by Audiovisual core

  # Description of the term list used in machine-readable metadata.
  description: This list includes terms borrowed by Audiovisual Core from the XMP Specification Part 2, EXIF schema for EXIF-specific properties (https://wwwimages2.adobe.com/content/dam/acom/en/devnet/xmp/pdfs/XMP%20SDK%20Release%20cc-2016-08/XMPSpecificationPart2.pdf).  Its terms are not dereferenceable.

# For existing term lists, MUST be namespace assigned by issuing organization. For TDWG
# term lists, MUST follow conventional TDWG IRI patterns.
- namespace_uri: http://ns.adobe.com/xap/1.0/rights/

  # Standard namespace abbreviation for the namespace IRI.
  pref_namespace_prefix: xmpRights

  # Database name for associated directories and files. MUST NOT contain spaces. SHOULD use
  # lowerCamelCase. Borrowed term lists SHOULD use naming convention of Darwin and Audiovisual Cores.
  database: xmpRights-for-ac

  # Set to true if namespace not issued by TDWG and in the rs.tdwg.org domain. 
  # Set to false if namespace issued by TDWG.
  borrowed: true

  # Set to true if a new term list that has never been processed before. Otherwise, set to false.
  new_term_list: false

  # Normally set to false except for non-versioned namespaces like decisions.
  utility_namespace: false

  # Path to hand-edited changes CSV file. Relative to process directory from which the
  # process.py script is run.
  modifications_file_path: ac-revisions/ac_fix_errors_2023-09-05/xmpRights-for-ac.csv

  # For TDWG-minted terms, SHOULD be set to empty string (Termlist IRI will be set to be
  # the same as the namespace IRI). For borrowed terms, mint an IRI that conforms to the 
  # TDWG termlist IRI pattern.
  termlist_uri: 'http://rs.tdwg.org/ac/xmpRights/'

  # Label used for the term list in machine-readable metadata.
  label: XMP Rights Management namespace terms from the XMP specification borrowed by Audiovisual Core

  # Description of the term list used in machine-readable metadata.
  description: This list includes terms borrowed by Audiovisual Core from the XMP Specification Part 1 - properties in the XMP Rights Management namespace (https://wwwimages2.adobe.com/content/dam/acom/en/devnet/xmp/pdfs/XMP%20SDK%20Release%20cc-2016-08/XMPSpecificationPart1.pdf).  Its terms are not dereferenceable.
