- contributor_iri: https://orcid.org/0000-0003-4365-3135
  contributor_literal: Steven J Baskauf
  contributor_role: lead author
  role_uri: http://www.wikidata.org/entity/Q482980
  affiliation: Vanderbilt University Heard Libraries
  affiliation_uri: http://www.wikidata.org/entity/Q16849893
